# Generated by Django 4.2.11 on 2024-06-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_color', models.PositiveSmallIntegerField(default=None)),
                ('nickname', models.CharField(max_length=13)),
                ('nickname_color', models.PositiveSmallIntegerField()),
                ('nickname_font', models.PositiveSmallIntegerField()),
                ('content', models.CharField(max_length=240)),
                ('content_color', models.PositiveSmallIntegerField()),
                ('content_font', models.PositiveSmallIntegerField()),
                ('emoji', models.CharField(default='', max_length=255)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('loves', models.PositiveBigIntegerField(default=0)),
                ('angries', models.PositiveBigIntegerField(default=0)),
                ('cries', models.PositiveBigIntegerField(default=0)),
                ('wows', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('sticky_note', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.stickynote')),
            ],
        ),
    ]
