# Generated by Django 4.2.13 on 2024-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('content', models.TextField()),
                ('replied_note_in', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('nickname_color', models.PositiveSmallIntegerField()),
                ('nickname_font', models.PositiveSmallIntegerField()),
                ('content', models.CharField(max_length=155)),
                ('content_color', models.PositiveSmallIntegerField()),
                ('content_font', models.PositiveSmallIntegerField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('loves', models.PositiveBigIntegerField(default=0)),
                ('angries', models.PositiveBigIntegerField(default=0)),
                ('cries', models.PositiveBigIntegerField(default=0)),
                ('wows', models.PositiveBigIntegerField(default=0)),
                ('replies', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
