# Generated by Django 4.2.11 on 2024-06-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='content',
            field=models.CharField(max_length=230),
        ),
    ]
