# Generated by Django 4.2.11 on 2024-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_stickynote_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='emoji',
            field=models.CharField(default='', max_length=255),
        ),
    ]
