# Generated by Django 4.2.11 on 2024-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_stickynote_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
    ]
