# Generated by Django 4.2.11 on 2024-06-15 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_stickynote_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='replies_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
