# Generated by Django 4.2.11 on 2024-06-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stickynote_note_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='replied_note_in',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='replies',
        ),
        migrations.AddField(
            model_name='replies',
            name='sticky_note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.stickynote'),
        ),
    ]
