# Generated by Django 4.2.11 on 2024-06-17 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_replies_replies_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
