# Generated by Django 4.2.11 on 2024-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_stickynote_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='replies_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
