# Generated by Django 4.2.11 on 2024-06-17 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_replies_replies_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='replies_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
